import { MigrationInterface, QueryRunner } from "typeorm";

export class $npmConfigName1664884771308 implements MigrationInterface {
    name = '$npmConfigName1664884771308'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`user_achievement\` (\`id\` int NOT NULL AUTO_INCREMENT, \`progress\` int NOT NULL DEFAULT '0', \`finished_date\` datetime NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`userId\` int NOT NULL, \`achievementId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_subscription\` (\`id\` int NOT NULL AUTO_INCREMENT, \`start_at\` datetime NOT NULL, \`end_at\` datetime NOT NULL, \`status\` tinyint NOT NULL, \`userId\` int NOT NULL, \`subscriptionPlanId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`rating_teacher\` (\`id\` int NOT NULL AUTO_INCREMENT, \`rating\` int NOT NULL, \`comment\` text NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`userId\` int NOT NULL, \`teacherId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`member_course\` (\`id\` int NOT NULL AUTO_INCREMENT, \`register_at\` datetime NOT NULL, \`studentId\` int NULL, \`livecourseId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`rating_course\` (\`id\` int NOT NULL AUTO_INCREMENT, \`rating\` int NOT NULL, \`comment\` text NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`userId\` int NOT NULL, \`livecourseId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`pronunciation_practice_tags_tag\` (\`pronunciationPracticeId\` int NOT NULL, \`tagId\` int NOT NULL, INDEX \`IDX_4c1cfaa13f4ed24df23d8d7617\` (\`pronunciationPracticeId\`), INDEX \`IDX_6ce8c4c867ce3ee9e19ee5ac49\` (\`tagId\`), PRIMARY KEY (\`pronunciationPracticeId\`, \`tagId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`live_course_tags_tag\` (\`liveCourseId\` int NOT NULL, \`tagId\` int NOT NULL, INDEX \`IDX_7c78a9314c6e11c835756f0725\` (\`liveCourseId\`), INDEX \`IDX_e888156bfb474eee39087a73b8\` (\`tagId\`), PRIMARY KEY (\`liveCourseId\`, \`tagId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reels_tags_tag\` (\`reelsId\` int NOT NULL, \`tagId\` int NOT NULL, INDEX \`IDX_cb6def84081574d581404e5eca\` (\`reelsId\`), INDEX \`IDX_5b5f1393261d6a0d8a17c5f8a6\` (\`tagId\`), PRIMARY KEY (\`reelsId\`, \`tagId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`transaction\` ADD \`userId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` ADD \`folderFlashcardId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`folder_flashcard\` ADD \`userId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`avatar\` ADD \`userId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`feedback\` ADD \`userId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` ADD \`staffProfileId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_profile\` ADD \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_practice\` ADD \`creatorId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_practice\` ADD \`levelId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`live_course\` ADD \`teacherId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`live_course\` ADD \`levelId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reels\` ADD \`creatorId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`notification\` ADD \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`bio\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`email\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD UNIQUE INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`phone_number\` varchar(11) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD UNIQUE INDEX \`IDX_01eea41349b6c9275aec646eee\` (\`phone_number\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`username\` varchar(16) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD UNIQUE INDEX \`IDX_78a916df40e02a9deb1c4b75ed\` (\`username\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`password\` varchar(16) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`score\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`roleId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` CHANGE \`meaning\` \`meaning\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` CHANGE \`image\` \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` CHANGE \`audio\` \`audio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`live_course\` CHANGE \`slots\` \`slots\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`fullname\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`fullname\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transaction\` ADD CONSTRAINT \`FK_605baeb040ff0fae995404cea37\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` ADD CONSTRAINT \`FK_96c9abdc2bdfc306e956b095629\` FOREIGN KEY (\`folderFlashcardId\`) REFERENCES \`folder_flashcard\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`folder_flashcard\` ADD CONSTRAINT \`FK_905211ef1f78e204b100ab23902\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_achievement\` ADD CONSTRAINT \`FK_2a418515c335cab7c5ba70c28b3\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_achievement\` ADD CONSTRAINT \`FK_843ecd1965f1aac694875674a18\` FOREIGN KEY (\`achievementId\`) REFERENCES \`achievement\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`avatar\` ADD CONSTRAINT \`FK_b6abb9e4579bb7fca4d823a5e66\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`feedback\` ADD CONSTRAINT \`FK_4a39e6ac0cecdf18307a365cf3c\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_subscription\` ADD CONSTRAINT \`FK_403d98d1638533c09f9b185929b\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_subscription\` ADD CONSTRAINT \`FK_3010dd7813f5c8f6359dc5ecab8\` FOREIGN KEY (\`subscriptionPlanId\`) REFERENCES \`subscription_plan\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` ADD CONSTRAINT \`FK_0b7d1ebb48f77c3dccdaacd69f4\` FOREIGN KEY (\`staffProfileId\`) REFERENCES \`staff_profile\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rating_teacher\` ADD CONSTRAINT \`FK_7715cd9ae8cc3120bc306179652\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rating_teacher\` ADD CONSTRAINT \`FK_554ee7617e04499dfa5ce3cf190\` FOREIGN KEY (\`teacherId\`) REFERENCES \`staff_profile\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_profile\` ADD CONSTRAINT \`FK_dcf4c54c6e051cb725aa69304df\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_practice\` ADD CONSTRAINT \`FK_41b78889d031703a1f4850b46c2\` FOREIGN KEY (\`creatorId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_practice\` ADD CONSTRAINT \`FK_7720ab04fc661b9301e35c81ba4\` FOREIGN KEY (\`levelId\`) REFERENCES \`level\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`member_course\` ADD CONSTRAINT \`FK_eca9ccaa9fd135cbc5454b8b837\` FOREIGN KEY (\`studentId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`member_course\` ADD CONSTRAINT \`FK_70cba9355b6baae1fd4b24c9e94\` FOREIGN KEY (\`livecourseId\`) REFERENCES \`live_course\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rating_course\` ADD CONSTRAINT \`FK_120e9462276086086df1d6a6f91\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rating_course\` ADD CONSTRAINT \`FK_ff65fd45eee60d9b94dba737206\` FOREIGN KEY (\`livecourseId\`) REFERENCES \`live_course\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`live_course\` ADD CONSTRAINT \`FK_3288d1aaf106a1b07d09b5258f5\` FOREIGN KEY (\`teacherId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`live_course\` ADD CONSTRAINT \`FK_daa784d4534061040a307eacc9d\` FOREIGN KEY (\`levelId\`) REFERENCES \`level\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reels\` ADD CONSTRAINT \`FK_820c8217367f2a5e30d2578741a\` FOREIGN KEY (\`creatorId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notification\` ADD CONSTRAINT \`FK_1ced25315eb974b73391fb1c81b\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_c28e52f758e7bbc53828db92194\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_practice_tags_tag\` ADD CONSTRAINT \`FK_4c1cfaa13f4ed24df23d8d7617b\` FOREIGN KEY (\`pronunciationPracticeId\`) REFERENCES \`pronunciation_practice\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_practice_tags_tag\` ADD CONSTRAINT \`FK_6ce8c4c867ce3ee9e19ee5ac49a\` FOREIGN KEY (\`tagId\`) REFERENCES \`tag\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`live_course_tags_tag\` ADD CONSTRAINT \`FK_7c78a9314c6e11c835756f0725d\` FOREIGN KEY (\`liveCourseId\`) REFERENCES \`live_course\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`live_course_tags_tag\` ADD CONSTRAINT \`FK_e888156bfb474eee39087a73b8d\` FOREIGN KEY (\`tagId\`) REFERENCES \`tag\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reels_tags_tag\` ADD CONSTRAINT \`FK_cb6def84081574d581404e5eca8\` FOREIGN KEY (\`reelsId\`) REFERENCES \`reels\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`reels_tags_tag\` ADD CONSTRAINT \`FK_5b5f1393261d6a0d8a17c5f8a65\` FOREIGN KEY (\`tagId\`) REFERENCES \`tag\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`reels_tags_tag\` DROP FOREIGN KEY \`FK_5b5f1393261d6a0d8a17c5f8a65\``);
        await queryRunner.query(`ALTER TABLE \`reels_tags_tag\` DROP FOREIGN KEY \`FK_cb6def84081574d581404e5eca8\``);
        await queryRunner.query(`ALTER TABLE \`live_course_tags_tag\` DROP FOREIGN KEY \`FK_e888156bfb474eee39087a73b8d\``);
        await queryRunner.query(`ALTER TABLE \`live_course_tags_tag\` DROP FOREIGN KEY \`FK_7c78a9314c6e11c835756f0725d\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_practice_tags_tag\` DROP FOREIGN KEY \`FK_6ce8c4c867ce3ee9e19ee5ac49a\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_practice_tags_tag\` DROP FOREIGN KEY \`FK_4c1cfaa13f4ed24df23d8d7617b\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_c28e52f758e7bbc53828db92194\``);
        await queryRunner.query(`ALTER TABLE \`notification\` DROP FOREIGN KEY \`FK_1ced25315eb974b73391fb1c81b\``);
        await queryRunner.query(`ALTER TABLE \`reels\` DROP FOREIGN KEY \`FK_820c8217367f2a5e30d2578741a\``);
        await queryRunner.query(`ALTER TABLE \`live_course\` DROP FOREIGN KEY \`FK_daa784d4534061040a307eacc9d\``);
        await queryRunner.query(`ALTER TABLE \`live_course\` DROP FOREIGN KEY \`FK_3288d1aaf106a1b07d09b5258f5\``);
        await queryRunner.query(`ALTER TABLE \`rating_course\` DROP FOREIGN KEY \`FK_ff65fd45eee60d9b94dba737206\``);
        await queryRunner.query(`ALTER TABLE \`rating_course\` DROP FOREIGN KEY \`FK_120e9462276086086df1d6a6f91\``);
        await queryRunner.query(`ALTER TABLE \`member_course\` DROP FOREIGN KEY \`FK_70cba9355b6baae1fd4b24c9e94\``);
        await queryRunner.query(`ALTER TABLE \`member_course\` DROP FOREIGN KEY \`FK_eca9ccaa9fd135cbc5454b8b837\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_practice\` DROP FOREIGN KEY \`FK_7720ab04fc661b9301e35c81ba4\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_practice\` DROP FOREIGN KEY \`FK_41b78889d031703a1f4850b46c2\``);
        await queryRunner.query(`ALTER TABLE \`staff_profile\` DROP FOREIGN KEY \`FK_dcf4c54c6e051cb725aa69304df\``);
        await queryRunner.query(`ALTER TABLE \`rating_teacher\` DROP FOREIGN KEY \`FK_554ee7617e04499dfa5ce3cf190\``);
        await queryRunner.query(`ALTER TABLE \`rating_teacher\` DROP FOREIGN KEY \`FK_7715cd9ae8cc3120bc306179652\``);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` DROP FOREIGN KEY \`FK_0b7d1ebb48f77c3dccdaacd69f4\``);
        await queryRunner.query(`ALTER TABLE \`user_subscription\` DROP FOREIGN KEY \`FK_3010dd7813f5c8f6359dc5ecab8\``);
        await queryRunner.query(`ALTER TABLE \`user_subscription\` DROP FOREIGN KEY \`FK_403d98d1638533c09f9b185929b\``);
        await queryRunner.query(`ALTER TABLE \`feedback\` DROP FOREIGN KEY \`FK_4a39e6ac0cecdf18307a365cf3c\``);
        await queryRunner.query(`ALTER TABLE \`avatar\` DROP FOREIGN KEY \`FK_b6abb9e4579bb7fca4d823a5e66\``);
        await queryRunner.query(`ALTER TABLE \`user_achievement\` DROP FOREIGN KEY \`FK_843ecd1965f1aac694875674a18\``);
        await queryRunner.query(`ALTER TABLE \`user_achievement\` DROP FOREIGN KEY \`FK_2a418515c335cab7c5ba70c28b3\``);
        await queryRunner.query(`ALTER TABLE \`folder_flashcard\` DROP FOREIGN KEY \`FK_905211ef1f78e204b100ab23902\``);
        await queryRunner.query(`ALTER TABLE \`flashcard\` DROP FOREIGN KEY \`FK_96c9abdc2bdfc306e956b095629\``);
        await queryRunner.query(`ALTER TABLE \`transaction\` DROP FOREIGN KEY \`FK_605baeb040ff0fae995404cea37\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`fullname\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`fullname\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`live_course\` CHANGE \`slots\` \`slots\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` CHANGE \`audio\` \`audio\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` CHANGE \`image\` \`image\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` CHANGE \`meaning\` \`meaning\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`roleId\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`score\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP INDEX \`IDX_78a916df40e02a9deb1c4b75ed\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`username\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP INDEX \`IDX_01eea41349b6c9275aec646eee\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`address\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`bio\``);
        await queryRunner.query(`ALTER TABLE \`notification\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`reels\` DROP COLUMN \`creatorId\``);
        await queryRunner.query(`ALTER TABLE \`live_course\` DROP COLUMN \`levelId\``);
        await queryRunner.query(`ALTER TABLE \`live_course\` DROP COLUMN \`teacherId\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_practice\` DROP COLUMN \`levelId\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_practice\` DROP COLUMN \`creatorId\``);
        await queryRunner.query(`ALTER TABLE \`staff_profile\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` DROP COLUMN \`staffProfileId\``);
        await queryRunner.query(`ALTER TABLE \`feedback\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`avatar\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`folder_flashcard\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`flashcard\` DROP COLUMN \`folderFlashcardId\``);
        await queryRunner.query(`ALTER TABLE \`transaction\` DROP COLUMN \`userId\``);
        await queryRunner.query(`DROP INDEX \`IDX_5b5f1393261d6a0d8a17c5f8a6\` ON \`reels_tags_tag\``);
        await queryRunner.query(`DROP INDEX \`IDX_cb6def84081574d581404e5eca\` ON \`reels_tags_tag\``);
        await queryRunner.query(`DROP TABLE \`reels_tags_tag\``);
        await queryRunner.query(`DROP INDEX \`IDX_e888156bfb474eee39087a73b8\` ON \`live_course_tags_tag\``);
        await queryRunner.query(`DROP INDEX \`IDX_7c78a9314c6e11c835756f0725\` ON \`live_course_tags_tag\``);
        await queryRunner.query(`DROP TABLE \`live_course_tags_tag\``);
        await queryRunner.query(`DROP INDEX \`IDX_6ce8c4c867ce3ee9e19ee5ac49\` ON \`pronunciation_practice_tags_tag\``);
        await queryRunner.query(`DROP INDEX \`IDX_4c1cfaa13f4ed24df23d8d7617\` ON \`pronunciation_practice_tags_tag\``);
        await queryRunner.query(`DROP TABLE \`pronunciation_practice_tags_tag\``);
        await queryRunner.query(`DROP TABLE \`rating_course\``);
        await queryRunner.query(`DROP TABLE \`member_course\``);
        await queryRunner.query(`DROP TABLE \`rating_teacher\``);
        await queryRunner.query(`DROP TABLE \`user_subscription\``);
        await queryRunner.query(`DROP TABLE \`user_achievement\``);
    }

}
