import { MigrationInterface, QueryRunner } from "typeorm";

export class $npmConfigName1668794932720 implements MigrationInterface {
    name = '$npmConfigName1668794932720'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`episode\` CHANGE \`video_file_name\` \`video_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_profile\` DROP COLUMN \`link_cv\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`name\` varchar(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`card_learned\` CHANGE \`learned_at\` \`learned_at\` date NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` DROP COLUMN \`term\``);
        await queryRunner.query(`ALTER TABLE \`flashcard\` ADD \`term\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` DROP COLUMN \`meaning\``);
        await queryRunner.query(`ALTER TABLE \`flashcard\` ADD \`meaning\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` DROP COLUMN \`example\``);
        await queryRunner.query(`ALTER TABLE \`flashcard\` ADD \`example\` varchar(30) NULL`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` CHANGE \`dueDate\` \`dueDate\` date NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`folder_flashcard\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`folder_flashcard\` ADD \`name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`folder_flashcard\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` DROP FOREIGN KEY \`FK_0b7d1ebb48f77c3dccdaacd69f4\``);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` DROP COLUMN \`position\``);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` ADD \`position\` varchar(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` CHANGE \`staffProfileId\` \`staffProfileId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_profile\` DROP COLUMN \`link_certification\``);
        await queryRunner.query(`ALTER TABLE \`staff_profile\` ADD \`link_certification\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`word_assessment\` DROP FOREIGN KEY \`FK_751f29c87b2d68c6bf77ba07fdb\``);
        await queryRunner.query(`ALTER TABLE \`word_assessment\` CHANGE \`result_pronunciation_id\` \`result_pronunciation_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`result_pronunciation_exercise\` DROP COLUMN \`pronounce_url\``);
        await queryRunner.query(`ALTER TABLE \`result_pronunciation_exercise\` ADD \`pronounce_url\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`result_pronunciation_exercise\` DROP COLUMN \`pronounce_id\``);
        await queryRunner.query(`ALTER TABLE \`result_pronunciation_exercise\` ADD \`pronounce_id\` varchar(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`result_identification_exercise\` DROP COLUMN \`chose_option\``);
        await queryRunner.query(`ALTER TABLE \`result_identification_exercise\` ADD \`chose_option\` varchar(60) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`identification_exercise\` DROP COLUMN \`true_option\``);
        await queryRunner.query(`ALTER TABLE \`identification_exercise\` ADD \`true_option\` varchar(60) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`identification_exercise\` DROP COLUMN \`false_option\``);
        await queryRunner.query(`ALTER TABLE \`identification_exercise\` ADD \`false_option\` varchar(60) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`episode\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`episode\` ADD \`name\` varchar(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`episode\` CHANGE \`fundamentals\` \`fundamentals\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`episode\` DROP COLUMN \`video_url\``);
        await queryRunner.query(`ALTER TABLE \`episode\` ADD \`video_url\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`episode\` DROP COLUMN \`video_id\``);
        await queryRunner.query(`ALTER TABLE \`episode\` ADD \`video_id\` varchar(30) NULL`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` DROP FOREIGN KEY \`FK_fd5d61d122a5e318d7835f66e96\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` ADD \`name\` varchar(70) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` DROP COLUMN \`poster\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` ADD \`poster\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` DROP COLUMN \`poster_id\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` ADD \`poster_id\` varchar(30) NULL`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` DROP COLUMN \`level\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` ADD \`level\` varchar(20) NOT NULL DEFAULT 'all'`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` CHANGE \`creatorId\` \`creatorId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_801282d422e1568ed4e512a6871\``);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`bio\` \`bio\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`address\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`address\` varchar(60) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`current_avatar\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`current_avatar\` varchar(100) NOT NULL DEFAULT 'https://deejayfarm.com/wp-content/uploads/2019/10/Profile-pic.jpg'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`email\` \`email\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`phone_number\` \`phone_number\` varchar(11) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`dob\` \`dob\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`last_online\` \`last_online\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`staff_profileId\` \`staff_profileId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` ADD CONSTRAINT \`FK_0b7d1ebb48f77c3dccdaacd69f4\` FOREIGN KEY (\`staffProfileId\`) REFERENCES \`staff_profile\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`word_assessment\` ADD CONSTRAINT \`FK_751f29c87b2d68c6bf77ba07fdb\` FOREIGN KEY (\`result_pronunciation_id\`) REFERENCES \`result_pronunciation_exercise\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` ADD CONSTRAINT \`FK_fd5d61d122a5e318d7835f66e96\` FOREIGN KEY (\`creatorId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_801282d422e1568ed4e512a6871\` FOREIGN KEY (\`staff_profileId\`) REFERENCES \`staff_profile\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_801282d422e1568ed4e512a6871\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` DROP FOREIGN KEY \`FK_fd5d61d122a5e318d7835f66e96\``);
        await queryRunner.query(`ALTER TABLE \`word_assessment\` DROP FOREIGN KEY \`FK_751f29c87b2d68c6bf77ba07fdb\``);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` DROP FOREIGN KEY \`FK_0b7d1ebb48f77c3dccdaacd69f4\``);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`staff_profileId\` \`staff_profileId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`last_online\` \`last_online\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`dob\` \`dob\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`phone_number\` \`phone_number\` varchar(11) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`email\` \`email\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`current_avatar\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`current_avatar\` varchar(255) NOT NULL DEFAULT ''https://deejayfarm.com/wp-content/uploads/2019/10/Profile-pic.jpg''`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`address\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`bio\` \`bio\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_801282d422e1568ed4e512a6871\` FOREIGN KEY (\`staff_profileId\`) REFERENCES \`staff_profile\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` CHANGE \`creatorId\` \`creatorId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` DROP COLUMN \`level\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` ADD \`level\` varchar(255) NOT NULL DEFAULT ''all''`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` DROP COLUMN \`poster_id\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` ADD \`poster_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` DROP COLUMN \`poster\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` ADD \`poster\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pronunciation_course\` ADD CONSTRAINT \`FK_fd5d61d122a5e318d7835f66e96\` FOREIGN KEY (\`creatorId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`episode\` DROP COLUMN \`video_id\``);
        await queryRunner.query(`ALTER TABLE \`episode\` ADD \`video_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`episode\` DROP COLUMN \`video_url\``);
        await queryRunner.query(`ALTER TABLE \`episode\` ADD \`video_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`episode\` CHANGE \`fundamentals\` \`fundamentals\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`episode\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`episode\` ADD \`name\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`identification_exercise\` DROP COLUMN \`false_option\``);
        await queryRunner.query(`ALTER TABLE \`identification_exercise\` ADD \`false_option\` varchar(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`identification_exercise\` DROP COLUMN \`true_option\``);
        await queryRunner.query(`ALTER TABLE \`identification_exercise\` ADD \`true_option\` varchar(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`result_identification_exercise\` DROP COLUMN \`chose_option\``);
        await queryRunner.query(`ALTER TABLE \`result_identification_exercise\` ADD \`chose_option\` varchar(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`result_pronunciation_exercise\` DROP COLUMN \`pronounce_id\``);
        await queryRunner.query(`ALTER TABLE \`result_pronunciation_exercise\` ADD \`pronounce_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`result_pronunciation_exercise\` DROP COLUMN \`pronounce_url\``);
        await queryRunner.query(`ALTER TABLE \`result_pronunciation_exercise\` ADD \`pronounce_url\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`word_assessment\` CHANGE \`result_pronunciation_id\` \`result_pronunciation_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`word_assessment\` ADD CONSTRAINT \`FK_751f29c87b2d68c6bf77ba07fdb\` FOREIGN KEY (\`result_pronunciation_id\`) REFERENCES \`result_pronunciation_exercise\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_profile\` DROP COLUMN \`link_certification\``);
        await queryRunner.query(`ALTER TABLE \`staff_profile\` ADD \`link_certification\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` CHANGE \`staffProfileId\` \`staffProfileId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` DROP COLUMN \`position\``);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` ADD \`position\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_experience\` ADD CONSTRAINT \`FK_0b7d1ebb48f77c3dccdaacd69f4\` FOREIGN KEY (\`staffProfileId\`) REFERENCES \`staff_profile\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`folder_flashcard\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`folder_flashcard\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`folder_flashcard\` ADD \`name\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` CHANGE \`dueDate\` \`dueDate\` date NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` DROP COLUMN \`example\``);
        await queryRunner.query(`ALTER TABLE \`flashcard\` ADD \`example\` varchar(200) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` DROP COLUMN \`meaning\``);
        await queryRunner.query(`ALTER TABLE \`flashcard\` ADD \`meaning\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`flashcard\` DROP COLUMN \`term\``);
        await queryRunner.query(`ALTER TABLE \`flashcard\` ADD \`term\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`card_learned\` CHANGE \`learned_at\` \`learned_at\` date NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_profile\` ADD \`link_cv\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`episode\` CHANGE \`video_id\` \`video_file_name\` varchar(255) NULL DEFAULT 'NULL'`);
    }

}
